# Generated by Django 5.1.5 on 2025-01-28 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_teammember_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="phone_number",
            field=models.CharField(
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format: 'XXX-XXX-XXXX' (e.g., 510-203-3908).",
                        regex="^\\d{3}-\\d{3}-\\d{4}$",
                    )
                ],
            ),
        ),
    ]
