# Generated by Django 5.1.5 on 2025-01-31 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_teammember_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid US phone number (e.g., +11234567890 or 1234567890).",
                        regex="^\\+?1?\\d{10}$",
                    )
                ],
            ),
        ),
    ]
