# Generated by Django 5.1.5 on 2025-01-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_teammember_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
