# Generated by Django 5.1.5 on 2025-02-01 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_alter_teammember_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter the phone number in a valid format. (Example: 1234567890)",
                        regex="^\\+?1?\\s?(\\d{3})[-.\\s]?(\\d{3})[-.\\s]?(\\d{4})$",
                    )
                ],
            ),
        ),
    ]
